version: "3.3"
services:
  api:
    build: .
    ports:
      - 3000:3000
    links:
      - postgres
  postgres:
    image: postgres:9.6.23
    volumes:
     - ./.postgres_data:/var/lib/postgresql/data